// =============================================================================
// Teacher profile photos — server-side upload, serve and cleanup rules.
// -----------------------------------------------------------------------------
// Photos go through the API into the private bucket "teachers_profile" and are
// served back by GET /api/teachers/photo, which checks the caller's school. All
// object-storage calls go through lib/storage.ts (the only module that knows which
// provider holds the files).
//
// Rules: real image bytes only (JPEG/PNG/WebP/GIF, checked by magic number, not by
// the browser's claimed type), 5 MB cap, extension chosen by us, path generated by us.
// =============================================================================

import crypto from "crypto";
import { ApiError, badRequest } from "@/lib/api/errors";
import { TEACHER_PHOTO_MAX_BYTES } from "@/lib/dto/teachers";
import { downloadFile, removeFiles, uploadFile } from "@/lib/storage";
import { buildTeacherPhotoUrl, TEACHERS_PROFILE_BUCKET } from "@/lib/teachers";

export type ImageKind = { mime: string; ext: string };

const startsWith = (bytes: Uint8Array, signature: number[], offset = 0): boolean =>
  signature.every((byte, index) => bytes[offset + index] === byte);

/**
 * Identify an image from its first bytes.
 *
 * Why it exists: the browser's Content-Type is just a claim. Checking the magic
 * number stops a script or SVG being stored (and later served) as "image/jpeg".
 *
 * @returns the real mime type and the extension to store it under, or null when it is not an allowed image
 */
export function sniffImageType(bytes: Uint8Array): ImageKind | null {
  if (bytes.length < 12) return null;
  if (startsWith(bytes, [0xff, 0xd8, 0xff])) return { mime: "image/jpeg", ext: "jpg" };
  if (startsWith(bytes, [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) {
    return { mime: "image/png", ext: "png" };
  }
  if (startsWith(bytes, [0x47, 0x49, 0x46, 0x38])) return { mime: "image/gif", ext: "gif" }; // "GIF8"
  if (startsWith(bytes, [0x52, 0x49, 0x46, 0x46]) && startsWith(bytes, [0x57, 0x45, 0x42, 0x50], 8)) {
    return { mime: "image/webp", ext: "webp" }; // "RIFF"....."WEBP"
  }
  return null;
}

/**
 * Validate an uploaded photo and read its bytes.
 *
 * @param file the multipart `photo` field
 * @returns the bytes and the detected image type
 * @throws 400 when it is empty, over 5 MB, not declared as an image, or not a real JPEG/PNG/WebP/GIF
 */
export async function readTeacherPhoto(file: File): Promise<{ bytes: ArrayBuffer; kind: ImageKind }> {
  if (file.size === 0) throw badRequest("Teacher photo is empty.");
  if (!file.type.startsWith("image/")) throw badRequest("Teacher photo must be an image file.");
  if (file.size > TEACHER_PHOTO_MAX_BYTES) throw badRequest("Teacher photo must be 5MB or smaller.");

  const bytes = await file.arrayBuffer();
  const kind = sniffImageType(new Uint8Array(bytes));
  if (!kind) throw badRequest("Teacher photo must be a JPEG, PNG, WebP or GIF image.");
  return { bytes, kind };
}

/**
 * Store a teacher's photo and return the URL to save on the teacher row.
 *
 * @param teacherId the teacher the photo belongs to (part of the generated path)
 * @param file the upload (validated here)
 * @returns the storage path and the app URL that serves it
 * @throws 400 for a bad file; 502 STORAGE_UPLOAD_FAILED when the storage provider refuses it
 */
export async function uploadTeacherPhoto(
  teacherId: string,
  file: File,
): Promise<{ path: string; url: string }> {
  const { bytes, kind } = await readTeacherPhoto(file);

  // Server-generated: nothing from the client's file name reaches the path.
  const path = `teachers/${teacherId}/${Date.now()}-${crypto.randomUUID()}.${kind.ext}`;

  const result = await uploadFile(TEACHERS_PROFILE_BUCKET, path, bytes, {
    contentType: kind.mime,
    ensureBucket: { public: false, fileSizeLimit: TEACHER_PHOTO_MAX_BYTES },
  });
  if (result.error) {
    console.error("[teacher-photo] upload failed:", result.error);
    throw new ApiError(502, "Could not store the photo. Please try again.", { code: "STORAGE_UPLOAD_FAILED" });
  }

  return { path, url: buildTeacherPhotoUrl(path) };
}

/**
 * The storage path behind a profile_photo URL, but ONLY when it is one of ours
 * for this teacher (`/api/teachers/photo?path=teachers/{teacherId}/...`). External
 * links and photos from before this module return null so we never delete them.
 */
export function managedPhotoPath(url: string | null | undefined, teacherId: string): string | null {
  if (!url || !url.startsWith("/api/teachers/photo")) return null;
  const queryStart = url.indexOf("?");
  if (queryStart === -1) return null;
  const path = new URLSearchParams(url.slice(queryStart + 1)).get("path");
  if (!path || path.includes("..") || !path.startsWith(`teachers/${teacherId}/`)) return null;
  return path;
}

/** Delete a stored photo. Best effort: a failed cleanup is logged, never thrown (the DB change already succeeded or failed on its own). */
export async function removeTeacherPhotoFile(path: string | null): Promise<void> {
  if (!path) return;
  const result = await removeFiles(TEACHERS_PROFILE_BUCKET, [path]);
  if (result.error) console.warn("[teacher-photo] could not remove stored photo:", result.error);
}

// A photo path is exactly teachers/{uuid}/{file}; anything else is refused before storage is touched.
const PHOTO_PATH_PATTERN = /^teachers\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/[A-Za-z0-9._-]+$/i;

/**
 * Split a `path` query value into the teacher id it belongs to, or null when it is not a
 * well-formed teacher photo path (blocks traversal and other buckets' layouts).
 */
export function parsePhotoPath(path: string | null | undefined): { teacherId: string } | null {
  const match = PHOTO_PATH_PATTERN.exec(String(path ?? "").trim());
  return match ? { teacherId: match[1] } : null;
}

const SERVABLE_IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp", "image/gif"]);

/**
 * Read a stored photo for GET /api/teachers/photo.
 *
 * @returns the bytes and an allow-listed image content type (never what the object claims blindly), or null when missing
 */
export async function readStoredTeacherPhoto(
  path: string,
): Promise<{ data: ArrayBuffer; contentType: string } | null> {
  const result = await downloadFile(TEACHERS_PROFILE_BUCKET, path);
  if (result.error || !result.data) return null;
  const sniffed = sniffImageType(new Uint8Array(result.data));
  const declared = result.contentType?.toLowerCase() ?? "";
  // Prefer the real bytes; fall back to the stored type only if it is a known image type.
  const contentType = sniffed?.mime ?? (SERVABLE_IMAGE_TYPES.has(declared) ? declared : null);
  return contentType ? { data: result.data, contentType } : null;
}
